In [2]:
from brtdevkit.data import Dataset
import numpy as np
df = Dataset.retrieve(name='Jupiter_20231004_implement_fps').to_dataframe()
velocities = np.array([d['speed'] for d in df['gps_can_data'] if 'speed' in d])
len(df) # 993
len(velocities) # 485, much data has no speed. 98% of this has speed > 0.

2023-10-10 13:44:12,591 - APIRequestor - ERROR - API error received | error_code : 403, error_message : {'extra': {'role_name': 'token_exchange'}, 'message': 'Role token_exchange is required to make this API call'}
ERROR:APIRequestor:API error received | error_code : 403, error_message : {'extra': {'role_name': 'token_exchange'}, 'message': 'Role token_exchange is required to make this API call'}
WARNING:root:Failed to refresh AWS Credential
WARNING:root:Some functionalities (S3, Athena, etc) not useable {'extra': {'role_name': 'token_exchange'}, 'message': 'Role token_exchange is required to make this API call'}

485

In [5]:
print(len(df))
df = df[df['bag_name'] != '10_04_2023-22_31_14']
print(len(df))

993
742

In [7]:
df

,artifact_debayeredrgb_0__id,artifact_debayeredrgb_0_content_hash,artifact_debayeredrgb_0_created_at,artifact_debayeredrgb_0_data_category,artifact_debayeredrgb_0_id,artifact_debayeredrgb_0_image,artifact_debayeredrgb_0_kind,artifact_debayeredrgb_0_project_name,artifact_debayeredrgb_0_s3_bucket,artifact_debayeredrgb_0_s3_key,...,state,system_name,teleop_request,teleop_response,updated_at,vadc_estimated_curvature,vehicle_bearing,vpu_position,was_compressed,weather_summary
125,651f0dd0f804810b52e49b4b,8e757f021ecf1ef3e82f7d4fef811b9f,2023-10-05T19:26:08.646000,eng,651f0dd0f804810b52e49b4b,651f0dd0f804810b52e49b4a,debayeredrgb,jupiter,brt-mesa-jupiter-images-eng,2023/10/05/e5e26c4a1f3742cf9bfa853dcba001ab-da...,...,Iowa,loamy_710,NaN,NaN,2023-10-05T19:26:09.495000,{'bag_name': 'loamy_710_0__10_04_2023-22_32_21...,82.757812,0,False,"{'datetime': '22:00:00', 'datetimeEpoch': 1696..."
126,651f0dd29b8292c23c05c863,465a2c307f9135106124066acad3141c,2023-10-05T19:26:10.627000,eng,651f0dd29b8292c23c05c863,651f0dd29b8292c23c05c861,debayeredrgb,jupiter,brt-mesa-jupiter-images-eng,2023/10/05/f3d812a563024d44a838c8b3c0cbb032-da...,...,Iowa,loamy_710,NaN,NaN,2023-10-05T19:26:10.960000,{'bag_name': 'loamy_710_0__10_04_2023-22_32_21...,82.757812,0,False,"{'datetime': '22:00:00', 'datetimeEpoch': 1696..."
127,651f0dd6c48b6dcce7e6074b,3e1e2d09409593d6aae2c051fd697942,2023-10-05T19:26:14.983000,eng,651f0dd6c48b6dcce7e6074b,651f0dd6c48b6dcce7e6074a,debayeredrgb,jupiter,brt-mesa-jupiter-images-eng,2023/10/05/a836ac7d79764b3aa3bd0a1c2509b50d-da...,...,Iowa,loamy_710,NaN,NaN,2023-10-05T19:26:15.521000,{'bag_name': 'loamy_710_0__10_04_2023-22_32_21...,82.757812,0,False,"{'datetime': '22:00:00', 'datetimeEpoch': 1696..."
128,651f0dd9175cb32bec52dbe5,5f8c077af20515aafb6c5fd89f011317,2023-10-05T19:26:17.954000,eng,651f0dd9175cb32bec52dbe5,651f0dd9175cb32bec52dbe4,debayeredrgb,jupiter,brt-mesa-jupiter-images-eng,2023/10/05/5ca49b6d673e42f587e2f7a51c468942-da...,...,Iowa,loamy_710,NaN,NaN,2023-10-05T19:26:18.770000,{'bag_name': 'loamy_710_0__10_04_2023-22_32_21...,77.984375,0,False,"{'datetime': '22:00:00', 'datetimeEpoch': 1696..."
129,651f0ddb7a541635a347f335,e2d1117ac7589f9795c20f3ee59b8a20,2023-10-05T19:26:19.819000,eng,651f0ddb7a541635a347f335,651f0ddb7a541635a347f333,debayeredrgb,jupiter,brt-mesa-jupiter-images-eng,2023/10/05/36ebb9261eb741d4ae82759f9b68d9b8-da...,...,Iowa,loamy_710,NaN,NaN,2023-10-05T19:26:20.169000,{'bag_name': 'loamy_710_0__10_04_2023-22_32_21...,77.984375,0,False,"{'datetime': '22:00:00', 'datetimeEpoch': 1696..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
988,651f1e1dee1ec5b92f34af0c,dae3805d028583269921e06e2e1246e0,2023-10-05T20:35:41.519000,eng,651f1e1dee1ec5b92f34af0c,651f1e1dee1ec5b92f34af0a,debayeredrgb,jupiter,brt-mesa-jupiter-images-eng,2023/10/05/fba880d13382442d915532566e5a5bd8-da...,...,unknown,loamy_710,NaN,NaN,2023-10-05T20:35:41.861000,NaN,NaN,1,False,"{'datetime': '22:00:00', 'datetimeEpoch': 1696..."
989,651f1e1e57a1ce7a997a44d8,16fbb7e5bf08c8d6fafdd175a70679dc,2023-10-05T20:35:42.659000,eng,651f1e1e57a1ce7a997a44d8,651f1e1e57a1ce7a997a44d7,debayeredrgb,jupiter,brt-mesa-jupiter-images-eng,2023/10/05/f7284e45c6664bf8953defa35288fe72-da...,...,unknown,loamy_710,NaN,NaN,2023-10-05T20:35:43.349000,NaN,NaN,1,False,"{'datetime': '22:00:00', 'datetimeEpoch': 1696..."
990,651f1e23bb3558c32636edd4,865556b528b221cd698ebaa200b87c94,2023-10-05T20:35:47.658000,eng,651f1e23bb3558c32636edd4,651f1e23bb3558c32636edd2,debayeredrgb,jupiter,brt-mesa-jupiter-images-eng,2023/10/05/02840aeacff74700a9cc13d12d9d3c12-da...,...,unknown,loamy_710,NaN,NaN,2023-10-05T20:35:48.100000,NaN,NaN,1,False,"{'datetime': '22:00:00', 'datetimeEpoch': 1696..."
991,651f1e26b9d7471817d56e66,8af0cf2186282a8ae4d784e940541738,2023-10-05T20:35:50.794000,eng,651f1e26b9d7471817d56e66,651f1e26b9d7471817d56e62,debayeredrgb,jupiter,brt-mesa-jupiter-images-eng,2023/10/05/4b4df3404e9a4f698cf7650a4217ecc6-da...,...,unknown,loamy_710,NaN,NaN,2023-10-05T20:35:51.111000,NaN,NaN,1,False,"{'datetime': '22:00:00', 'datetimeEpoch': 1696..."
992,651f1e278f8e7829f309a420,658214b022e7bb3246382be53055d045,2023-10-05T20:35:51.869000,eng,651f1e278f8e7829f309a420,651f1e278f8e7829f309a41f,debayeredrgb,jupiter,brt-mesa-jupiter-images-eng,2023/10/05/939353bc48154b56b3f9277184448b4b-da...,...,unknown,loamy_710,NaN,NaN,2023-10-05T20:35:52.603000,NaN,NaN,1,False,"{'datetime': '22:00:00', 'datetimeEpoch': 1696..."